var goods = [
	{
		id: 1,
		name: "Товар 1",
		price: 100,
		count: 50,
		img1: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-1.jpg',
		img2: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-2.jpg',
	}, {
		id: 2,
		name: "Товар 2",
		price: 50,
		count: 100,
		img1: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-3.jpg',
		img2: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-4.jpg',
	}, {
		id: 3,
		name: "Товар 3",
		price: 50,
		count: 100,
		img1: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-5.jpg',
		img2: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-6.jpg',
	}, {
		id: 4,
		name: "Товар 4",
		price: 50,
		count: 100,
		img1: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-7.jpg',
		img2: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-8.jpg',
	}, {
		id: 5,
		name: "Товар 5",
		price: 100,
		count: 50,
		img1: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-8.jpg',
		img2: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-7.jpg',
	}, {
		id: 6,
		name: "Товар 6",
		price: 50,
		count: 100,
		img1: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-6.jpg',
		img2: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-5.jpg',
	}, {
		id: 7,
		name: "Товар 7",
		price: 50,
		count: 100,
		img1: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-4.jpg',
		img2: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-3.jpg',
	}, {
		id: 8,
		name: "Товар 8",
		price: 50,
		count: 100,
		img1: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-2.jpg',
		img2: 'http://bestjquery.com/tutorial/product-grid/demo5/images/img-1.jpg',
	},
];